const allVideo =[
    {    hash:"#cricket #Testmatch",
         title: "Top 20 wickets of the 2020-21 international season" ,
         id: 'OTtiuN6aBf4',
         thumb:'https://i.ytimg.com/vi/OTtiuN6aBf4/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBaYfEdU-h-7sx7LbiTVrGFWEiWwg',
         thumbgif:'./GIF/g1.webp',
         vdate:"1,182,963 views•Feb 1, 2021",
         des:"From spectacular fielding in the women's white-ball games in September through to the dramatic dismissals of the Australia-India men's Test series, we count down the top 20 wickets of the 2020-21 international season on Aussie soil",
         ppic:"https://yt3.ggpht.com/ytc/AAUvwnjdwk_H9e0CxY8VlVJ0zibRkwlsUkhH1WlxSQRpz58=s48-c-k-c0x00ffffff-no-rj",
         pnam:"cricket.com.au",
         psub:"7.91M subscribers",
         com:"1,149 Comments",
         comp1:"https://yt3.ggpht.com/ytc/AAUvwnh0ALfFtH1n1_tPdiHDsbVQH3S3NvH5zPYiqQ=s48-c-k-c0x00ffffff-no-rj",
         comn1:"Manas A Ranade",
         com1:"Cricket Australia is confused between best wickets and best fielding efforts😂",
         comp2:"https://yt3.ggpht.com/ytc/AAUvwngTWYijodPnftUxhGnCX09ibjoo_1Sq6Fnt0w=s48-c-k-c0x00ffffff-no-rj",
         comn2:"Vinod Talwal",
         com2:"This was more of best fielding efforts than wickets",
         likes:"21k",
         dislikes:"400",
         comments:[]
        },

    {    hash:"#Faded #AlanWalker #EDM",
        title: "Alan Walker - Faded" ,
        id: '60ItHLz5WEA',
        thumb:'https://i.ytimg.com/vi/60ItHLz5WEA/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDkccnygK86gFDqVaK7ilG1E8Wehw',
        thumbgif:'./GIF/g2.webp',
        vdate:"3,013,735,133 views•Dec 4, 2015",
        des:"You were the shadow to my light\nDid you feel us\nAnother start\nYou fade away\nAfraid our aim is out of sight\nWanna see us\nAlive\nWhere are you now\nWhere are you now\nWhere are you now\nWas it all in my fantasy\nWhere are you now\nWere you only imaginary\nWhere are you now\nAtlantis\nUnder the sea\nUnder the sea\nWhere are you now\nAnother dream\nThe monsters running wild inside of me\nI'm faded\nI'm faded\nSo lost\nI'm faded\nI'm faded\nSo lost\nI'm faded\nThese shallow waters, never met\nWhat I needed\nI'm letting go\nA deeper dive\nEternal silence of the sea\nI'm breathing\nAlive\nWhere are you now\nWhere are you now\nUnder the bright\nBut faded lights\nYou set my heart on fire\nWhere are you now\nWhere are you now\nWhere are you now\nAtlantis\nUnder the sea\nUnder the sea\nWhere are you now\nAnother dream\nThe monsters running wild inside of me\nI'm faded\nI'm faded",
        ppic:"https://yt3.ggpht.com/ytc/AAUvwnh1eFKTAxPHwgR9l1yUcC3XXYBtTC1hWnZy5pwWwA=s48-c-k-c0x00ffffff-no-rj-mo",
        pnam:"Alan Walker",
        psub:"38.8M subscribers",
        com:"1,201,276 Comments",
        comp1:"https://yt3.ggpht.com/ytc/AAUvwnj_cymFmxQTJ_wj9P4opCBmLbneEcw0eBfkcNLlew=s48-c-k-c0x00ffffff-no-rj",
        comn1:"The Walker",
        com1:"It doesn't matter what language you use in a song. Through it you can reach the hearts of people, make them feel, live, dance and much more",
        comp2:"https://yt3.ggpht.com/ytc/AAUvwnhLBQ2iWiE8wDmMwIIV5TCJ2xirrANQjjFF-LEB=s48-c-k-c0x00ffffff-no-rj",
        comn2:"Debanjan official",
        com2:"Fun fact : After 5 years the comment section is always active",
        likes:"9.1k",
        dislikes:"1k",
        comments:[]
       },

       {    hash:"#Superman #ManofSteel",
       title: "Man of Steel - Official Trailer 3 [HD]" ,
       id: 'T6DJcgm3wNY',
       thumb:'https://i.ytimg.com/vi/T6DJcgm3wNY/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBU5lg3LxgljnP9954K88AkWNe9NQ',
       thumbgif:'./GIF/g3.webp',
       vdate:"46,804,982 views•Apr 17, 2013",
       des:"http://manofsteel.com​ http://www.facebook.com/manofsteel​ In theaters June 14th.From Warner Bros. and Legendary Pictures comes Man of Steel, starring Henry Cavill, directed by Zach Snyder. The film also stars Amy Adams, Diane Lane, Kevin Costner, Michael Shannon, Russell Crowe, Antje Traue, Ayelet Zurer, Henry Lennix, Christopher Meloni and Laurence Fishburne.http://manofsteel.com​ http://www.facebook.com/manofsteel​ In theaters June 14th.From Warner Bros. and Legendary Pictures comes Man of Steel, starring Henry Cavill, directed by Zach Snyder. The film also stars Amy Adams, Diane Lane, Kevin Costner, Michael Shannon, Russell Crowe, Antje Traue, Ayelet Zurer, Henry Lennix, Christopher Meloni and Laurence Fishburne.",
       ppic:"https://yt3.ggpht.com/ytc/AAUvwnhIJZKqH3FkWGKNP-OufNVlj7qHMVzPtIItQ8DYOg=s48-c-k-c0x00ffffff-no-rj",
       pnam:"Warner Bros. Pictures",
       psub:"9.58M subscribers",
       com:"61,428 Comments",
       comp1:"https://yt3.ggpht.com/ytc/AAUvwnjVQdEiXi1shGoJmBFqKZ-n2XbGd4oCZ7-dhq-SKg=s48-c-k-c0x00ffffff-no-rj",
       comn1:"Full Fat Videos",
       com1:"This trailer rocked so hard back in the day. I couldn't believe how well Zimmer had lived up to Williams with that Superman theme.",
       comp2:"https://yt3.ggpht.com/ytc/AAUvwnjHXuzYHOYV6es80haTdYH9y6cbHk4S93InRNRHyg=s48-c-k-c0x00ffffff-no-rj",
       comn2:"Paul John",
       com2:"This is the number of people who badly want Man of Steel 2 👇🏽",
       likes:"7.3k",
       dislikes:"450",
       comments:[]
      },
      
      {    hash:"#controls #goals #football",
         title: "Ball Controls that can't be repeated in football" ,
         id: 'sb7DHMFdNKE',
         thumb:'https://i.ytimg.com/vi/xSsiS304iY8/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBNLQvk3sr2MHJ4fs6Wnsd9jnE14g',
         thumbgif:'./GIF/g4.webp',
         vdate:"1,528,084 views•Mar 13, 2021",
         des:"👍 Ball Controls that can't be repeated in football 👍 IF YOU LIKE SOCCER JOIN THE CHANNEL: https://goo.gl/bhZX1O​ #controls​ #goals​ #football 👍 Ball Controls that can't be repeated in football 👍 IF YOU LIKE SOCCER JOIN THE CHANNEL: https://goo.gl/bhZX1O​ #controls​ #goals​ #football 👍 Ball Controls that can't be repeated in football 👍 IF YOU LIKE SOCCER JOIN THE CHANNEL: https://goo.gl/bhZX1O​ #controls​ #goals​ #football",
         ppic:"https://yt3.ggpht.com/ytc/AAUvwng_7qPG-x8aocG3UKUmbx_BvzLqXw6Mx3CNK921kA=s48-c-k-c0x00ffffff-no-rj",
         pnam:"SportsHD",
         psub:"4.13M subscribers",
         com:"638 Comments",
         comp1:"https://yt3.ggpht.com/ytc/AAUvwnjo6LcqvaldGgy9IcITlUbbcu4wje0Rt57Xv0cwEA=s48-c-k-c0x00ffffff-no-rj",
         comn1:"Lol Lol",
         com1:"Никто: Совершенно никто:НУ ВОТ ВООБЩЕ НИКТО ПОНИМАЕТЕ:Перевод ютуба: Органы управления Шаровые, которые не могут быть повторены",
         comp2:"https://yt3.ggpht.com/ytc/AAUvwng7cxrY4SuU3MA0ym3fUflP27D6zQC0-ftaqNNtoA=s48-c-k-c0x00ffffff-no-rj",
         comn2:"Football Club",
         com2:"all respect to Zidane because that one was awsome",
         likes:"55k",
         dislikes:"1.3k",
         comments:[]
        },

        {    hash:"#RajkummarRao #JanhviKapoor #VarunSharma",
         title: "Lut Gaye (Full Song) Emraan Hashmi, Yukti | Jubin N, Tanishk B, Manoj M | Bhushan K | Radhika-Vinay" ,
         id: 'sCbbMZ-q4-I',
         thumb:'https://i.ytimg.com/vi/sCbbMZ-q4-I/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBLsipfulT_oHwwNWVrSXQmMcwnLQ',
         thumbgif:'./GIF/g5.webp',
         vdate:"240,515,231 views•Feb 17, 2021",
         des:"Gulshan Kumar & T-Series presents Bhushan Kumar's Lut Gaye; a romantic ballad composed by Tanishk Bagchi, penned by Manoj Muntashir and sung by Jubin Nautiyal featuring Emraan Hashmi, and Yukti Thareja. The video is directed by Radhika Rao and Vinay Sapru.",
         ppic:"https://yt3.ggpht.com/ytc/AAUvwnhEWQNuA-mjqxLqnxia6OrJooWWGnyn8KCw3yNbriQ=s48-c-k-c0x00ffffff-no-rj",
         pnam:"T-Series",
         psub:"176M subscribers",
         com:"149,643 Comments",
         comp1:"https://yt3.ggpht.com/ytc/AAUvwniQpzVqOnwoH63hCsYryc7xf-iaqjP5mR0elVLxdw=s48-c-k-c0x00ffffff-no-rj",
         comn1:"WSF",
         com1:"Waiting for 1Billion Views 🔥🔥👍",
         comp2:"https://yt3.ggpht.com/ytc/AAUvwnhLd3RrnQlrfjCqqjeuQb7a3qhsfwHktMjqqPKO=s48-c-k-c0x00ffffff-no-rj",
         comn2:"Akshat Shukla",
         com2:"What a lovely pair of Jubin & Emraan",
         likes:"3.5k",
         dislikes:"233",
         comments:[]
        },

        {    hash:"#9 ON TRENDING",
         title: "Bhai Behan Aur F.I.R. | BakLol Video" ,
         id: '5snrv_aOOLU',
         thumb:'https://i.ytimg.com/vi/5snrv_aOOLU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDJy13yJR5qSpgh1ksMrvmKh5L7Pg',
         thumbgif:'./GIF/g6.webp',
         vdate:"6,578,166 views•Mar 15, 2021",
         des:"This is a comedy video of a brother & sister who went to Police Station to file the complaint against each other.  For Behind The Scenes & More Updates Follow us on Instagram : @baklolvideo http://instagram.com/baklolvideo​​ Snapchat- pankajbaklol Starring: Pankaj Sharma Sanjhalika Shokeen ( Sanjhalika Vlog ) Aditi Sharma Vibhu Varshney ( Guddu Bhaiya ) Yash Srivastava Yogesh Kathuria Kamal Bhardwaj Suprit Thakur Ft.Aditi Sharma Shoot by- Nitish Goel Editing- Pankaj Sharma Script-  Kundan  Color- Pankaj Sharma Manager - Aashish Bhardwaj  Thumbnail - SP Design   Search Tags: Behan Bhai  Bhai behan aur FIR  Behan Bhai aur Police Baklol Video behan bhai Behan bhai funny vide Thank You for Watching",
         ppic:"https://yt3.ggpht.com/ytc/AAUvwng9xP-Y9jS2XqRt7413cFYRtd9IctSp_GaduiuMdw=s48-c-k-c0x00ffffff-no-rj",
         pnam:"BakLol Video",
         psub:"8.26M subscribers",
         com:"9,327 Comments",
         comp1:"https://yt3.ggpht.com/ytc/AAUvwng9xP-Y9jS2XqRt7413cFYRtd9IctSp_GaduiuMdw=s48-c-k-c0x00ffffff-no-rj",
         comn1:"BakLol Video",
         com1:"Part 2 ke bare me kya bolte ho dosto ? <3 comment karo jaldi se",
         comp2:"https://yt3.ggpht.com/ytc/AAUvwnhEwxWlSgWLApU3X60kH_HYfl0nCARG_fz7rp7I=s48-c-k-c0x00ffffff-no-rj",
         comn2:"The Cosine Solar",
         com2:"Part -2 ke baare me Jaldi se comment kro",
         likes:"157k",
         dislikes:"21k",
         comments:[]
        },

        {    hash:"#KGFChapter2​ #KGFChapter2Teaser​",
         title: "KGF Chapter2 TEASER |Yash|Sanjay Dutt|Raveena Tandon|Srinidhi Shetty|Prashanth Neel|Vijay Kiragandur" ,
         id: 'EfxU3M47jTQ',
         thumb:'https://i.ytimg.com/vi/EfxU3M47jTQ/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCWhyfIcFKU6jYfmYQoewGvkQ4CxA',
         thumbgif:'./GIF/g7.webp',
         vdate:"4,350,381 views•Feb 13, 2021",
         des:"Official Teaser of KGF Chapter 2 Presented by Ritesh Sidhwani, Farhan Akhtar and AA Films Written and Directed by Prashanth Neel Produced by Vijay Kiragandur Starring: Yash, Sanjay Dutt, Srinidhi Shetty, Raveena Tandon, Prakash Raj, Malvika Avinash, Achyuth Kumar, Ayyappa P. Sharma, Rao Ramesh, Eshwari Rao, Archana Jois, T. S. Nagabharana, Saran, Avinash, Lakki Lakshman, Vashishta Simha, Harish Rai, Dinesh Mangalore, Tarak, Ramachandra Raju, Vinay Bidappa, Ashok Sharma, Mohan Juneja, Govinda Gowda, John Kokken, Srinivas Murthy Director of Photography: Bhuvan Gowda Sound Design, Music & Background Score: Ravi BasrurDirection Team: Kirtan Nadagouda, Dhool Prakash, Bhargav N, Prashanth Hosmane, Chandan L, Yuvindraja, Nishanth Varma, Sanjay Muruli Muddenahally, Ghattimutthu Shashidhar, Abhijith Gorachi, Shiva Kumar, Mithilesh Gowda, Akash Thaargar, Akash Rambo, Farman Ullah Cameraman Team: Sandy, Prajwal Gowda, Kumar Gowda, Sagar Gowda, Manuraj Still - M G Narayan(Nani) Executive Producer: Karthik Gowda, K. V Rama Rao Editor: Ujwal Kulkarni Production Design: Shivakumar Action: Anbariv Choreography: Harsha, MohanDubbing: Anand Y. S Costume Designer: Yogi G Raj, Sania Sardhariya, Navin Shetty, Ashwin Mawle, Hassan Khan Dialogues: Chandramouli.M, Dr. Suri, Prashanth Neel Sound Effects: Nanndhu J & Team Production Managers: K S Champakadama,Gagan Murthy, S KumarProduction Incharge: Chidanand, Suresh Shankarananhalli, ShashikanthDI & VFX: Unify MediaVFX Supervisor: Konda Reddy SureshColorist: Fergus Hally, Ashwath Marketing: Likitha Reddy, Naren Marol, Anil Kumar, Shreya Unchalli, Manoj Shetty, Lakshmi Narayan Digital Media PR: Prasad Bhimanadham Art Department: Venkata Chalapathi, Kiran Kumar, Ramesh, Shankar, Sunil, Deva, Abhi, Shyam, Koti, GouthamFemale Humming Solo Voice: Ananya Bhat",
         ppic:"https://yt3.ggpht.com/ytc/AAUvwng3MfqUJ3pCca8WWXQBnzVw6f3IBnDPfssul8-G=s48-c-k-c0x00ffffff-no-rj",
         pnam:"Excel Movies",
         psub:"2.13M subscribers",
         com:"2,714 Comments",
         comp1:"https://yt3.ggpht.com/ytc/AAUvwniOBm1AO8aMJ1p3IjxhgNmWfKuXI8X67_dV2tPoAA=s48-c-k-c0x00ffffff-no-rj",
         comn1:"RK Records",
         com1:"Ab bollywood tu to gyaa❤🤣🤣🤣 Rocking star yash ko kon kon love krta hai??❤❤❤ KGF is Brand ❤❤👌",
         comp2:"https://yt3.ggpht.com/ytc/AAUvwnjRAVxWd8zlCvvObEtqg0LAAtBdk-KxzPA9UpWtJQ=s48-c-k-c0x00ffffff-no-rj",
         comn2:"Creative Thinker Anik",
         com2:"my heart touching movie👄💋🌹continued watching..react anymore plz👄💋🌹",
         likes:"92k",
         dislikes:"2.7k",
         comments:[]
        },

        {    hash:"#RajkummarRao #JanhviKapoor #VarunSharma",
         title: "Lut Gaye (Full Song) Emraan Hashmi, Yukti | Jubin N, Tanishk B, Manoj M | Bhushan K | Radhika-Vinay" ,
         id: 'sCbbMZ-q4-I',
         thumb:'https://i.ytimg.com/vi/sCbbMZ-q4-I/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBLsipfulT_oHwwNWVrSXQmMcwnLQ',
         thumbgif:'./GIF/g5.webp',
         vdate:"240,515,231 views•Feb 17, 2021",
         des:"Gulshan Kumar & T-Series presents Bhushan Kumar's Lut Gaye; a romantic ballad composed by Tanishk Bagchi, penned by Manoj Muntashir and sung by Jubin Nautiyal featuring Emraan Hashmi, and Yukti Thareja. The video is directed by Radhika Rao and Vinay Sapru.",
         ppic:"https://yt3.ggpht.com/ytc/AAUvwnhEWQNuA-mjqxLqnxia6OrJooWWGnyn8KCw3yNbriQ=s48-c-k-c0x00ffffff-no-rj",
         pnam:"T-Series",
         psub:"176M subscribers",
         com:"149,643 Comments",
         comp1:"https://yt3.ggpht.com/ytc/AAUvwniQpzVqOnwoH63hCsYryc7xf-iaqjP5mR0elVLxdw=s48-c-k-c0x00ffffff-no-rj",
         comn1:"WSF",
         com1:"Waiting for 1Billion Views 🔥🔥👍",
         comp2:"https://yt3.ggpht.com/ytc/AAUvwnhLd3RrnQlrfjCqqjeuQb7a3qhsfwHktMjqqPKO=s48-c-k-c0x00ffffff-no-rj",
         comn2:"Akshat Shukla",
         com2:"What a lovely pair of Jubin & Emraan",
         likes:"3.5k",
         dislikes:"233",
         comments:[]
        },

        {    hash:"#9 ON TRENDING",
         title: "Bhai Behan Aur F.I.R. | BakLol Video" ,
         id: '5snrv_aOOLU',
         thumb:'https://i.ytimg.com/vi/5snrv_aOOLU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDJy13yJR5qSpgh1ksMrvmKh5L7Pg',
         thumbgif:'./GIF/g6.webp',
         vdate:"6,578,166 views•Mar 15, 2021",
         des:"This is a comedy video of a brother & sister who went to Police Station to file the complaint against each other.  For Behind The Scenes & More Updates Follow us on Instagram : @baklolvideo http://instagram.com/baklolvideo​​ Snapchat- pankajbaklol Starring: Pankaj Sharma Sanjhalika Shokeen ( Sanjhalika Vlog ) Aditi Sharma Vibhu Varshney ( Guddu Bhaiya ) Yash Srivastava Yogesh Kathuria Kamal Bhardwaj Suprit Thakur Ft.Aditi Sharma Shoot by- Nitish Goel Editing- Pankaj Sharma Script-  Kundan  Color- Pankaj Sharma Manager - Aashish Bhardwaj  Thumbnail - SP Design   Search Tags: Behan Bhai  Bhai behan aur FIR  Behan Bhai aur Police Baklol Video behan bhai Behan bhai funny vide Thank You for Watching",
         ppic:"https://yt3.ggpht.com/ytc/AAUvwng9xP-Y9jS2XqRt7413cFYRtd9IctSp_GaduiuMdw=s48-c-k-c0x00ffffff-no-rj",
         pnam:"BakLol Video",
         psub:"8.26M subscribers",
         com:"9,327 Comments",
         comp1:"https://yt3.ggpht.com/ytc/AAUvwng9xP-Y9jS2XqRt7413cFYRtd9IctSp_GaduiuMdw=s48-c-k-c0x00ffffff-no-rj",
         comn1:"BakLol Video",
         com1:"Part 2 ke bare me kya bolte ho dosto ? <3 comment karo jaldi se",
         comp2:"https://yt3.ggpht.com/ytc/AAUvwnhEwxWlSgWLApU3X60kH_HYfl0nCARG_fz7rp7I=s48-c-k-c0x00ffffff-no-rj",
         comn2:"The Cosine Solar",
         com2:"Part -2 ke baare me Jaldi se comment kro",
         likes:"157k",
         dislikes:"21k",
         comments:[]
        },

        {    hash:"#KGFChapter2​ #KGFChapter2Teaser​",
         title: "KGF Chapter2 TEASER |Yash|Sanjay Dutt|Raveena Tandon|Srinidhi Shetty|Prashanth Neel|Vijay Kiragandur" ,
         id: 'EfxU3M47jTQ',
         thumb:'https://i.ytimg.com/vi/EfxU3M47jTQ/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCWhyfIcFKU6jYfmYQoewGvkQ4CxA',
         thumbgif:'./GIF/g7.webp',
         vdate:"4,350,381 views•Feb 13, 2021",
         des:"Official Teaser of KGF Chapter 2 Presented by Ritesh Sidhwani, Farhan Akhtar and AA Films Written and Directed by Prashanth Neel Produced by Vijay Kiragandur Starring: Yash, Sanjay Dutt, Srinidhi Shetty, Raveena Tandon, Prakash Raj, Malvika Avinash, Achyuth Kumar, Ayyappa P. Sharma, Rao Ramesh, Eshwari Rao, Archana Jois, T. S. Nagabharana, Saran, Avinash, Lakki Lakshman, Vashishta Simha, Harish Rai, Dinesh Mangalore, Tarak, Ramachandra Raju, Vinay Bidappa, Ashok Sharma, Mohan Juneja, Govinda Gowda, John Kokken, Srinivas Murthy Director of Photography: Bhuvan Gowda Sound Design, Music & Background Score: Ravi BasrurDirection Team: Kirtan Nadagouda, Dhool Prakash, Bhargav N, Prashanth Hosmane, Chandan L, Yuvindraja, Nishanth Varma, Sanjay Muruli Muddenahally, Ghattimutthu Shashidhar, Abhijith Gorachi, Shiva Kumar, Mithilesh Gowda, Akash Thaargar, Akash Rambo, Farman Ullah Cameraman Team: Sandy, Prajwal Gowda, Kumar Gowda, Sagar Gowda, Manuraj Still - M G Narayan(Nani) Executive Producer: Karthik Gowda, K. V Rama Rao Editor: Ujwal Kulkarni Production Design: Shivakumar Action: Anbariv Choreography: Harsha, MohanDubbing: Anand Y. S Costume Designer: Yogi G Raj, Sania Sardhariya, Navin Shetty, Ashwin Mawle, Hassan Khan Dialogues: Chandramouli.M, Dr. Suri, Prashanth Neel Sound Effects: Nanndhu J & Team Production Managers: K S Champakadama,Gagan Murthy, S KumarProduction Incharge: Chidanand, Suresh Shankarananhalli, ShashikanthDI & VFX: Unify MediaVFX Supervisor: Konda Reddy SureshColorist: Fergus Hally, Ashwath Marketing: Likitha Reddy, Naren Marol, Anil Kumar, Shreya Unchalli, Manoj Shetty, Lakshmi Narayan Digital Media PR: Prasad Bhimanadham Art Department: Venkata Chalapathi, Kiran Kumar, Ramesh, Shankar, Sunil, Deva, Abhi, Shyam, Koti, GouthamFemale Humming Solo Voice: Ananya Bhat",
         ppic:"https://yt3.ggpht.com/ytc/AAUvwng3MfqUJ3pCca8WWXQBnzVw6f3IBnDPfssul8-G=s48-c-k-c0x00ffffff-no-rj",
         pnam:"Excel Movies",
         psub:"2.13M subscribers",
         com:"2,714 Comments",
         comp1:"https://yt3.ggpht.com/ytc/AAUvwniOBm1AO8aMJ1p3IjxhgNmWfKuXI8X67_dV2tPoAA=s48-c-k-c0x00ffffff-no-rj",
         comn1:"RK Records",
         com1:"Ab bollywood tu to gyaa❤🤣🤣🤣 Rocking star yash ko kon kon love krta hai??❤❤❤ KGF is Brand ❤❤👌",
         comp2:"https://yt3.ggpht.com/ytc/AAUvwnjRAVxWd8zlCvvObEtqg0LAAtBdk-KxzPA9UpWtJQ=s48-c-k-c0x00ffffff-no-rj",
         comn2:"Creative Thinker Anik",
         com2:"my heart touching movie👄💋🌹continued watching..react anymore plz👄💋🌹",
         likes:"92k",
         dislikes:"2.7k",
         comments:[]
        }

]

let comarray=[]

const updateComment=(id,comment,cid,like,dislike)=>{
   allVideo.find((item,i)=>{
       
 if(item.id===id)
     {
         item.comments.unshift({"id":id,"coment":comment,"comentID":cid,"likes":{"id":cid,"amount":like},"dislikes":{"id":cid,"amount":dislike}})
        }
        comarray[i]=item.comments
      
     })
     
    }

export { allVideo,updateComment,comarray}